# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MothersLove' do
  pod 'React',
  :path => "../node_modules/react-native",
  :inhibit_warnings => true,
  :subspecs => [
    "Core",
    "ART",
    "RCTActionSheet",
    "RCTAnimation",
    "RCTCameraRoll",
    "RCTGeolocation",
    "RCTImage",
    "RCTLinkingIOS",
    "RCTNetwork",
    "RCTText",
    "RCTVibration",
    "RCTWebSocket",
    "DevSupport",
    "CxxBridge"
  ]
  pod 'yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga",
    :inhibit_warnings => true
  pod 'DoubleConversion',
    :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec",
    :inhibit_warnings => true


  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MothersLove

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'react-native-video', :path => '../node_modules/react-native-video'

  target 'MothersLoveTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    
    targets_to_ignore = %w(React yoga)
    
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

  end
end
