# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MothersLove' do
  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MothersLove

  

  platform :ios, '9.0'
  target 'MothersLoveTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MothersLove-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MothersLove-tvOS

  target 'MothersLove-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
