// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from motherslove.djinni

#import <Foundation/Foundation.h>
@class MTLDehaze;


@interface MTLDehaze : NSObject

+ (nullable MTLDehaze *)create;

- (nonnull NSString *)dehaze:(nonnull NSString *)uri
                       media:(nonnull NSString *)media;

@end
