// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from motherslove.djinni

#import <Foundation/Foundation.h>
@class MTLHelloWorld;


@interface MTLHelloWorld : NSObject

+ (nullable MTLHelloWorld *)create;

- (nonnull NSString *)getHelloWorld;

- (int32_t)add:(int32_t)a
             b:(int32_t)b;

@end
