// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from motherslove.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>

namespace motherslove {

class HelloWorld {
public:
    virtual ~HelloWorld() {}

    static std::shared_ptr<HelloWorld> create();

    virtual std::string get_hello_world() = 0;

    virtual int32_t add(int32_t a, int32_t b) = 0;
};

}  // namespace motherslove
